name: Build WhatsApp Router Production
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref:  main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::production-v0.0.2
      - name: Login to ECR
        uses: docker/login-action@v1 
        with:
          registry: 242357350604.dkr.ecr.sa-east-1.amazonaws.com/whatsapp-router
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and push - Rapidpro Image
        id: docker_build1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: 242357350604.dkr.ecr.sa-east-1.amazonaws.com/whatsapp-router:${{ steps.vars.outputs.tag }}
          no-cache: true
